import type { CSSProperties } from "react";

type Styles = Record<string, CSSProperties>;

export const S: Styles = {
  root: {
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    maxWidth: 460,
    margin: "0 auto",
    padding: 16,
    background: "#13131f",
    minHeight: "100vh",
    color: "#e8e8f0",
  },
  header: { textAlign: "center", marginBottom: 20, paddingTop: 8 },
  title: { fontSize: 22, fontWeight: 700, margin: 0, letterSpacing: -0.5 },
  subtitle: { fontSize: 13, color: "#888", margin: "4px 0 0" },
  tabs: { display: "flex", gap: 8, marginBottom: 16 },
  tab: {
    flex: 1,
    padding: "10px 0",
    background: "#1e1e2e",
    border: "1px solid #2a2a3a",
    borderRadius: 10,
    color: "#888",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 500,
  },
  tabActive: {
    flex: 1,
    padding: "10px 0",
    background: "#2a2a4a",
    border: "1px solid #5858a8",
    borderRadius: 10,
    color: "#c8c8ff",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
  },
  card: {
    background: "#1a1a2e",
    borderRadius: 14,
    padding: 20,
    border: "1px solid #2a2a3a",
  },
  modeRow: { display: "flex", gap: 8, marginBottom: 18 },
  modeBtn: {
    flex: 1,
    padding: "10px 0",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#999",
    fontSize: 14,
    cursor: "pointer",
  },
  modeBtnActive: {
    flex: 1,
    padding: "10px 0",
    background: "#3a2020",
    border: "1px solid #c44",
    borderRadius: 8,
    color: "#faa",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
  },
  modeBtnActiveBlue: {
    flex: 1,
    padding: "10px 0",
    background: "#1a2a4a",
    border: "1px solid #48f",
    borderRadius: 8,
    color: "#8bf",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
  },
  label: {
    display: "block",
    fontSize: 12,
    color: "#888",
    marginBottom: 6,
    marginTop: 14,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#e8e8f0",
    fontSize: 16,
    outline: "none",
    boxSizing: "border-box",
  },
  inputNum: {
    width: "100%",
    padding: "10px 8px",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#e8e8f0",
    fontSize: 18,
    fontWeight: 700,
    textAlign: "center",
    outline: "none",
    boxSizing: "border-box",
  },
  painRow: { display: "flex", gap: 3 },
  painBtn: {
    flex: 1,
    padding: "6px 0",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    transition: "background .15s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
  },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  chip: {
    padding: "6px 12px",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 20,
    color: "#999",
    fontSize: 13,
    cursor: "pointer",
  },
  chipActive: {
    padding: "6px 12px",
    background: "#2a2044",
    border: "1px solid #a070e0",
    borderRadius: 20,
    color: "#d0b0ff",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 600,
  },
  chipActiveOrange: {
    padding: "6px 12px",
    background: "#3a2a18",
    border: "1px solid #e09040",
    borderRadius: 20,
    color: "#ffcc80",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 600,
  },
  bpRow: { display: "flex", gap: 10, alignItems: "flex-end" },
  bpField: { flex: 1 },
  bpSlash: { fontSize: 28, color: "#555", paddingBottom: 8, fontWeight: 300 },
  saveBtn: {
    width: "100%",
    padding: "14px 0",
    marginTop: 20,
    background: "linear-gradient(135deg, #5050c0, #7040b0)",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  saveBtnDone: {
    width: "100%",
    padding: "14px 0",
    marginTop: 20,
    background: "#2a6a2a",
    border: "none",
    borderRadius: 10,
    color: "#afffaf",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  filterRow: { display: "flex", gap: 6, marginBottom: 14 },
  filterBtn: {
    flex: 1,
    padding: "7px 0",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#888",
    fontSize: 13,
    cursor: "pointer",
  },
  filterActive: {
    flex: 1,
    padding: "7px 0",
    background: "#2a2a4a",
    border: "1px solid #5858a8",
    borderRadius: 8,
    color: "#c8c8ff",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 600,
  },
  monthGroup: { marginBottom: 4 },
  monthHeader: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    background: "none",
    border: "none",
    borderBottom: "1px solid #2a2a3a",
    color: "#c8c8f0",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  monthMeta: { display: "flex", alignItems: "center", gap: 8 },
  monthCount: {
    fontSize: 12,
    color: "#888",
    background: "#252540",
    padding: "2px 8px",
    borderRadius: 10,
  },
  empty: { textAlign: "center", color: "#666", padding: 30 },
  entry: { padding: "14px 0", borderBottom: "1px solid #2a2a3a" },
  entryHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  entryDate: { fontSize: 13, color: "#888", flex: 1 },
  badge: {
    fontSize: 16,
    background: "#2a1818",
    padding: "2px 8px",
    borderRadius: 6,
  },
  badgeBlue: {
    fontSize: 16,
    background: "#182838",
    padding: "2px 8px",
    borderRadius: 6,
  },
  delBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: 14,
    cursor: "pointer",
    padding: "2px 6px",
  },
  entryRow: { display: "flex", alignItems: "center", gap: 10 },
  painDot: {
    fontSize: 13,
    fontWeight: 700,
    padding: "3px 10px",
    borderRadius: 12,
    color: "#000",
  },
  entryDetail: { fontSize: 13, color: "#aaa" },
  entryTriggers: { fontSize: 12, color: "#999", marginTop: 4 },
  entryNote: { fontSize: 13, color: "#bbb", marginTop: 4 },
  bpValue: { fontSize: 20, fontWeight: 700, color: "#8bf" },
  pulseValue: { fontSize: 14, color: "#f88" },
  exportBtn: {
    width: "100%",
    padding: "12px 0",
    marginTop: 16,
    background: "linear-gradient(135deg, #1a6a3a, #2a8a4a)",
    border: "none",
    borderRadius: 8,
    color: "#cfc",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  importBtn: {
    display: "block",
    width: "100%",
    padding: "12px 0",
    marginTop: 8,
    background: "linear-gradient(135deg, #2a4a6a, #3a5a8a)",
    border: "none",
    borderRadius: 8,
    color: "#bdf",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
    boxSizing: "border-box",
  },
  resetBtn: {
    width: "100%",
    padding: 10,
    marginTop: 8,
    background: "none",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#666",
    fontSize: 13,
    cursor: "pointer",
  },
  storageNote: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginTop: 14,
    lineHeight: 1.5,
  },
  updateBar: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    background: "#2a2a4a",
    borderTop: "1px solid #5858a8",
    color: "#c8c8ff",
    fontSize: 14,
    zIndex: 1000,
  },
  updateBtn: {
    padding: "8px 20px",
    background: "linear-gradient(135deg, #5050c0, #7040b0)",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
};

export const PS: Styles = {
  trigger: {
    width: "100%",
    padding: "10px 12px",
    background: "#222238",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#e8e8f0",
    fontSize: 15,
    cursor: "pointer",
    textAlign: "left",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  panel: {
    marginTop: 8,
    background: "#1e1e30",
    border: "1px solid #333",
    borderRadius: 10,
    padding: 12,
  },
  calHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  navBtn: {
    background: "none",
    border: "none",
    color: "#8888cc",
    fontSize: 22,
    cursor: "pointer",
    padding: "4px 10px",
    lineHeight: 1,
  },
  monthLabel: { fontSize: 14, fontWeight: 600, color: "#c8c8f0" },
  weekRow: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 2,
    marginBottom: 4,
  },
  weekDay: { fontSize: 11, color: "#666", textAlign: "center", padding: 2 },
  dayGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 2,
  },
  dayBtn: {
    width: "100%",
    aspectRatio: "1",
    background: "#252540",
    border: "none",
    borderRadius: 8,
    color: "#ccc",
    fontSize: 13,
    cursor: "pointer",
  },
  daySelected: { background: "#5050c0", color: "#fff", fontWeight: 700 },
  dayToday: { border: "1px solid #5050c0", color: "#aaf" },
  dayEmpty: { width: "100%" },
  timeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 12,
    paddingTop: 10,
    borderTop: "1px solid #2a2a3a",
  },
  nowBtn: {
    padding: "6px 14px",
    background: "#2a2a4a",
    border: "1px solid #5050c0",
    borderRadius: 8,
    color: "#aaf",
    fontSize: 13,
    cursor: "pointer",
    marginRight: "auto",
  },
  timePickerGroup: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  timeArrow: {
    background: "none",
    border: "none",
    color: "#888",
    fontSize: 10,
    cursor: "pointer",
    padding: "2px 8px",
    lineHeight: 1,
  },
  timeValue: {
    fontSize: 22,
    fontWeight: 700,
    color: "#e8e8f0",
    fontVariantNumeric: "tabular-nums",
    minWidth: 36,
    textAlign: "center",
  },
  timeInput: {
    width: 40,
    fontSize: 22,
    fontWeight: 700,
    color: "#e8e8f0",
    fontVariantNumeric: "tabular-nums",
    textAlign: "center",
    background: "#252540",
    border: "1px solid #333",
    borderRadius: 6,
    padding: "2px 0",
    outline: "none",
    boxSizing: "border-box",
  },
  timeColon: { fontSize: 22, fontWeight: 700, color: "#666" },
};
